[zuul][tempest] Use tempest image built from master instead of antelope
Resolving the following error by using a newer version of the tempest
image i.e. built from master instead of the version tagged for antelope

telemetry_tempest_plugin.scenario.test_telemetry_integration_prometheus.PrometheusGabbiTest.test_ceilometer_sg_core_integration
-------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/var/lib/tempest/external-plugins/.venv/lib64/python3.9/site-packages/telemetry_tempest_plugin/scenario/utils.py", line 66, in test
    run_test(self, test_dir, filename)

      File "/var/lib/tempest/external-plugins/.venv/lib64/python3.9/site-packages/telemetry_tempest_plugin/scenario/utils.py", line 41, in run_test
    handlers=runner.initialize_handlers([]),

    TypeError: initialize_handlers() missing 1 required positional argument: 'local_handlers'